### ISSUE TITLE
Poll results throw exception

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1274]
```[2021-11-16T22:26:44.011132+01:00] gewisweb.ERROR: Laminas\Form\Exception\DomainException: Laminas\Form\View\Helper\FormButton::render expects either button content as the second argument, or that the element provided has a label value; neither found in /code/vendor/laminas/laminas-form/src/View/Helper/FormButton.php:82 Stack trace:
#0 /code/vendor/laminas/laminas-form/src/View/Helper/FormButton.php(66): Laminas\Form\View\Helper\FormButton->render(Object(Laminas\Form\Element\Submit), NULL)
#1 [internal function]: Laminas\Form\View\Helper\FormButton->__invoke(Object(Laminas\Form\Element\Submit))
#2 /code/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(391): call_user_func_array(Object(Laminas\Form\View\Helper\FormButton), Array)
#3 /code/module/Frontpage/view/frontpage/poll/index.phtml(91): Laminas\View\Renderer\PhpRenderer->__call('formButton', Array)
#4 /code/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(500): include('/code/module/Fr...')
#5 /code/vendor/laminas/laminas-view/src/View.php(200): Laminas\View\Renderer\PhpRenderer->render(NULL)
#6 /code/vendor/laminas/laminas-view/src/View.php(229): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#7 /code/vendor/laminas/laminas-view/src/View.php(193): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel)) 
#8 /code/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(98): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#9 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#10 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#11 /code/vendor/laminas/laminas-mvc/src/Application.php(360): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#12 /code/vendor/laminas/laminas-mvc/src/Application.php(341): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#13 /code/public/index.php(20): Laminas\Mvc\Application->run()
#14 {main} [] []```

**Comment by Koen1999** [comment]
Probably a bug introduced in #1264
