### ISSUE TITLE
"My Activities" page throws `QueryException`

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1341]
```
[2022-01-30T10:59:33.401469+01:00] gewisweb.ERROR: Doctrine\ORM\Query\QueryException: SELECT a FROM Activity\Model\Activity a, Activity\Model\Activity a WHERE a.endTime > :now AND a.organ = :organ in /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:27 Stack trace:
#0 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(534): Doctrine\ORM\Query\QueryException::dqlError('SELECT a FROM A...')
#1 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(991): Doctrine\ORM\Query\Parser->semanticalError('line 0, col 65 ...', Array)
#2 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1794): Doctrine\ORM\Query\Parser->AliasIdentificationVariable() #3 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1635): Doctrine\ORM\Query\Parser->RangeVariableDeclaration() #4 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1373): Doctrine\ORM\Query\Parser->IdentificationVariableDeclaration()
#5 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(918): Doctrine\ORM\Query\Parser->FromClause()
#6 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(887): Doctrine\ORM\Query\Parser->SelectStatement()
#7 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(297): Doctrine\ORM\Query\Parser->QueryLanguage()
#8 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(397): Doctrine\ORM\Query\Parser->getAST()
#9 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(271): Doctrine\ORM\Query\Parser->parse()
#10 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(283): Doctrine\ORM\Query->parse()
#11 /code/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1160): Doctrine\ORM\Query->_doExecute()
#12 /code/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1115): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1)
#13 /code/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(863): Doctrine\ORM\AbstractQuery->execute(NULL, 1)
#14 /code/module/Activity/src/Mapper/Activity.php(161): Doctrine\ORM\AbstractQuery->getResult()
#15 /code/module/Activity/src/Mapper/Activity.php(72): Activity\Mapper\Activity->getUpcomingActivitiesByOrgan(Object(DoctrineORMModule\Proxy\__CG__\Decision\Model\Organ))
#16 /code/module/Activity/src/Service/ActivityQuery.php(236): Activity\Mapper\Activity->getUpcomingActivitiesForMember(Object(User\Model\User))
#17 /code/module/Activity/src/Controller/ActivityController.php(92): Activity\Service\ActivityQuery->getUpcomingActivities('my')
#18 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Activity\Controller\ActivityController->indexAction()
#19 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#20 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#21 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#22 /code/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#23 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#24 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#25 /code/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#26 /code/public/index.php(20): Laminas\Mvc\Application->run()
#27 {main} 
Next Doctrine\ORM\Query\QueryException: [Semantical Error] line 0, col 65 near 'a WHERE a.endTime': Error: 'a' is already defined. in /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:49 Stack trace:
#0 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(534): Doctrine\ORM\Query\QueryException::semanticalError('line 0, col 65 ...', Object(Doctrine\ORM\Query\QueryException))
#1 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(991): Doctrine\ORM\Query\Parser->semanticalError('line 0, col 65 ...', Array)
#2 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1794): Doctrine\ORM\Query\Parser->AliasIdentificationVariable()
#3 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1635): Doctrine\ORM\Query\Parser->RangeVariableDeclaration()
#4 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1373): Doctrine\ORM\Query\Parser->IdentificationVariableDeclaration()
#5 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(918): Doctrine\ORM\Query\Parser->FromClause()
#6 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(887): Doctrine\ORM\Query\Parser->SelectStatement()
#7 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(297): Doctrine\ORM\Query\Parser->QueryLanguage()
#8 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(397): Doctrine\ORM\Query\Parser->getAST()
#9 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(271): Doctrine\ORM\Query\Parser->parse()
#10 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(283): Doctrine\ORM\Query->parse()
#11 /code/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1160): Doctrine\ORM\Query->_doExecute()
#12 /code/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1115): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1)
#13 /code/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(863): Doctrine\ORM\AbstractQuery->execute(NULL, 1)
#14 /code/module/Activity/src/Mapper/Activity.php(161): Doctrine\ORM\AbstractQuery->getResult()
#15 /code/module/Activity/src/Mapper/Activity.php(72): Activity\Mapper\Activity->getUpcomingActivitiesByOrgan(Object(DoctrineORMModule\Proxy\__CG__\Decision\Model\Organ))
#16 /code/module/Activity/src/Service/ActivityQuery.php(236): Activity\Mapper\Activity->getUpcomingActivitiesForMember(Object(User\Model\User)) #17 /code/module/Activity/src/Controller/ActivityController.php(92): Activity\Service\ActivityQuery->getUpcomingActivities('my')
#18 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Activity\Controller\ActivityController->indexAction() #19 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#20 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#21 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#22 /code/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#23 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#24 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#25 /code/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#26 /code/public/index.php(20): Laminas\Mvc\Application->run()
#27 {main} [] []
```

**Comment by tomudding** [comment]
Whoopsies!
