### ISSUE TITLE
Viewing non-existent poll results in unhandled operations on `null` object

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1343]
```
[2022-01-29T00:21:56.821523+01:00] gewisweb.ERROR: Error: Call to a member function getApprover() on null in /code/module/Frontpage/src/Service/Poll.php:101 Stack trace:
#0 /code/module/Frontpage/src/Controller/PollController.php(98): Frontpage\Service\Poll->getPoll(537)
#1 /code/module/Frontpage/src/Controller/PollController.php(66): Frontpage\Controller\PollController->obtainPoll()
#2 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Frontpage\Controller\PollController->indexAction()
#3 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#4 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#5 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#6 /code/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#7 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#8 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#9 /code/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#10 /code/public/index.php(20): Laminas\Mvc\Application->run() 
#11 {main} [] []
```

**Comment by tomudding** [comment]
Good find! Can be easily fixed by adding a `null` check or using `?->` instead (why wasn't there one in the first place?). However, it does require additional `null` checking in all functions which use `getPoll()`, as none of them do that at this point in time.
