### ISSUE TITLE
Watermarking summaries does not always succeed because limited cache resources

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1344]
```
[2022-01-29T10:20:27.467231+01:00] gewisweb.ERROR: ImagickException: cache resources exhausted `/code/public/data/d5/929hrbv24h9urb249hbv249uhvb249.pdf' @ error/cache.c/OpenPixelCache/4095 in /code/module/Application/src/Service/WatermarkService.php:92 Stack trace:
#0 /code/module/Application/src/Service/WatermarkService.php(92): Imagick->mergeImageLayers(14)
#1 /code/module/Application/src/Service/FileStorage.php(183): Application\Service\WatermarkService->watermarkPdf('public/data/d5/...')
#2 /code/module/Education/src/Service/Exam.php(160): Application\Service\FileStorage->downloadFile('d5/ur23burvhb2h...', '0HV100-Nicky va...', true)
#3 /code/module/Education/src/Controller/EducationController.php(101): Education\Service\Exam->getExamDownload(3841)
#4 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Education\Controller\EducationController->downloadAction()
#5 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#6 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#7 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#8 /code/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#9 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#10 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#11 /code/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#12 /code/public/index.php(20): Laminas\Mvc\Application->run()
#13 {main} [] []
```

**Comment by tomudding** [comment]
We may have to move to something we can `exec` or `shell_exec`, that way we do not have to convert all the pages separately, store them in the cache, and join them together in PHP (which is not that efficient).

Or we just layer the text onto the PDF instead of merging it with the page, but we'd have to discuss that with the board.

**Comment by Koen1999** [comment]
While the layering is effective, I heard people complain about it. Actually reading and using the pdfs became less convenient.

Perhaps we should also consult the CBC to check how many resources we have available and whether increasing the cache size is permissible.

**Comment by Koen1999** [comment]
The config changes made in https://github.com/GEWIS/gewisweb/pull/1329/commits/a7237459167b4a64b3a6ee6b1a0c79c9f2925427 may actually already address this problem partially.
