### ISSUE TITLE
Company jobs of specific type but without actual job (but with trailing slash) causes 500 internal server error

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1447]
https://github.com/GEWIS/gewisweb/blob/407213e4ce9c17323c0809c0ef9d104b62ec46c5/module/Company/src/Controller/CompanyController.php#L180-L184

appears to have no purpose and results in the following error:

> Error: Call to a member function getPackage() on null in /code/module/Company/view/company/company/jobs.phtml:4 Stack trace:
    #0 /code/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519): include()
    \#1 /code/vendor/laminas/laminas-view/src/View.php(194): Laminas\View\Renderer\PhpRenderer->render(NULL)
    \#2 /code/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
    \#3 /code/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
    \#4 /code/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(98): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
    \#5 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
    \#6 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
    \#7 /code/vendor/laminas/laminas-mvc/src/Application.php(360): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
    \#8 /code/vendor/laminas/laminas-mvc/src/Application.php(341): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
    \#9 /code/public/index.php(23): Laminas\Mvc\Application->run()
    \#10 {main} [] []

Three solutions possible: 1) return 404 instead, 2) switch the template for the `ViewModel` (same as for `jobListAction()`), or 3) redirect to `jobListAction()`.

**Comment by tomudding** [comment]
Best solution is actually changing the quantifier in the route regex from `*` to `+`:

https://github.com/GEWIS/gewisweb/blob/407213e4ce9c17323c0809c0ef9d104b62ec46c5/module/Company/config/module.config.php#L105

Then the whole `if`-statement for `$jobSlugName` can be removed.
