### ISSUE TITLE
External activity sign-ups potentially broken

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisweb#1508]
### Current behaviour

> Laminas\Session\Exception\InvalidArgumentException: Name passed to container is invalid; must consist of alphanumerics, backslashes and underscores only in /code/vendor/laminas/laminas-session/src/AbstractContainer.php:74 Stack trace: 
#0 /code/vendor/laminas/laminas-captcha/src/AbstractWord.php(261): Laminas\Session\AbstractContainer->__construct('Laminas_Form_Ca...') 
#1 /code/vendor/laminas/laminas-captcha/src/AbstractWord.php(289): Laminas\Captcha\AbstractWord->getSession() 
#2 /code/vendor/laminas/laminas-captcha/src/AbstractWord.php(403): Laminas\Captcha\AbstractWord->getWord() 
#3 /code/vendor/laminas/laminas-validator/src/ValidatorChain.php(254): Laminas\Captcha\AbstractWord->isValid(Array, Array) 
#4 /code/vendor/laminas/laminas-inputfilter/src/Input.php(416): Laminas\Validator\ValidatorChain->isValid(Array, Array) 
#5 /code/vendor/laminas/laminas-inputfilter/src/BaseInputFilter.php(280): Laminas\InputFilter\Input->isValid(Array) 
#6 /code/vendor/laminas/laminas-inputfilter/src/BaseInputFilter.php(233): Laminas\InputFilter\BaseInputFilter->validateInputs(Array, Array, NULL) 
#7 /code/vendor/laminas/laminas-form/src/Form.php(481): Laminas\InputFilter\BaseInputFilter->isValid() 
#8 /code/module/Activity/src/Controller/ActivityController.php(357): Laminas\Form\Form->isValid() 
#9 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Activity\Controller\ActivityController->externalSignupAction() 
#10 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent)) 
#11 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure)) 
#12 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent)) 
#13 /code/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response)) 
#14 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent)) 
#15 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure)) 
#16 /code/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent)) 
#17 /code/public/index.php(23): Laminas\Mvc\Application->run() 
#18 {main} [] []

### Steps to reproduce

Unknown

### Website version

v2.8.6

**Comment by tomudding** [comment]
This is a bit weird, as the default id that is used for the session name does not violate the requirements.

**Comment by tomudding** [comment]
I have not been able to reproduce this and I have seen plenty of external sign-ups since September.
